---
title: "Plan de manejo Predio Las Palmas, Valdivia Chile"
output: pdf_document
date: "`r format(Sys.Date(), '%d %B %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(broom)
options(kableExtra.latex.load_packages = FALSE)
library(kableExtra)
```

# Introducción

Este documento contiene información dasómetrica de dos plantaciones ubicadas en el predio Las Palmas, Valdivia Chile. Especificamente, existe una plantación de Coihue-Olivillo y una de Raulí. 

# Métodos

## Área de estudio

hacer mapa y descripicón de área de estudio

## Ánalisis de datos.

En cada plantación se establecieron 5 parcelas de 500 $m^{2}$ cada una, donde se registró la especie, su diamétro a la altura del pecho (**dap**), posición sociológica, sanidad y forma (en una escala de 1 a 3), además se realizó la medición de la altura de una muestra de Raulí y Coihue (Cuadro 1 ) para poder predecir la altura y volumen de la plantación 

El procesamiento de datos consitio en un resumen de las principales variables dasometricas a nivel de rodal y a nivel de parcela. 

# Resultados


